In [95]:
import pandas as pd

In [96]:
train_data = pd.read_csv('train_Vidya2.csv')

In [97]:
test_data = pd.read_csv('test_Vidya2.csv')

In [98]:
train_data.shape

(7109, 22)

In [99]:
test_data.shape

(2925, 21)

In [100]:
train_data.head()

PRT_ID        AREA  INT_SQFT   DATE_SALE  DIST_MAINROAD  N_BEDROOM  \
0  P03210  Karapakkam      1004  04-05-2011            131        1.0   
1  P09411  Anna Nagar      1986  19-12-2006             26        2.0   
2  P01812       Adyar       909  04-02-2012             70        1.0   
3  P05346   Velachery      1855  13-03-2010             14        3.0   
4  P06210  Karapakkam      1226  05-10-2009             84        1.0   

   N_BATHROOM  N_ROOM SALE_COND PARK_FACIL     ...      UTILITY_AVAIL  STREET  \
0         1.0       3  AbNormal        Yes     ...             AllPub   Paved   
1         1.0       5  AbNormal         No     ...             AllPub  Gravel   
2         1.0       3  AbNormal        Yes     ...                ELO  Gravel   
3         2.0       5    Family         No     ...            NoSewr    Paved   
4         1.0       3  AbNormal        Yes     ...             AllPub  Gravel   

  MZZONE QS_ROOMS QS_BATHROOM  QS_BEDROOM  QS_OVERALL  REG_FEE  COMMIS  \
0      A      4.0         3.9         4.9       4.330   380000  144400   
1     RH      4.9         4.2         2.5       3.765   760122  304049   
2     RL      4.1         3.8         2.2       3.090   421094   92114   
3      I      4.7         3.9         3.6       4.010   356321   77042   
4      C      3.0         2.5         4.1       3.290   237000   74063   

   SALES_PRICE  
0      7600000  
1     21717770  
2     13159200  
3      9630290  
4      7406250  

[5 rows x 22 columns]

In [101]:
train_data['AREA'].value_counts()

Chrompet      1681
Karapakkam    1363
KK Nagar       996
Velachery      979
Anna Nagar     783
Adyar          773
T Nagar        496
Chrompt          9
Chormpet         6
Chrmpet          6
TNagar           5
Karapakam        3
Ana Nagar        3
Velchery         2
Ann Nagar        2
Adyr             1
KKNagar          1
Name: AREA, dtype: int64

In [102]:
test_data['AREA'].value_counts()

Chrompet      721
Karapakkam    515
Velachery     418
KK Nagar      413
Anna Nagar    334
Adyar         298
T Nagar       214
Velchery        4
Karapakam       3
Chrmpet         2
Ann Nagar       1
Chrompt         1
Chormpet        1
Name: AREA, dtype: int64

In [103]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7109 entries, 0 to 7108
Data columns (total 22 columns):
PRT_ID           7109 non-null object
AREA             7109 non-null object
INT_SQFT         7109 non-null int64
DATE_SALE        7109 non-null object
DIST_MAINROAD    7109 non-null int64
N_BEDROOM        7108 non-null float64
N_BATHROOM       7104 non-null float64
N_ROOM           7109 non-null int64
SALE_COND        7109 non-null object
PARK_FACIL       7109 non-null object
DATE_BUILD       7109 non-null object
BUILDTYPE        7109 non-null object
UTILITY_AVAIL    7109 non-null object
STREET           7109 non-null object
MZZONE           7109 non-null object
QS_ROOMS         7109 non-null float64
QS_BATHROOM      7109 non-null float64
QS_BEDROOM       7109 non-null float64
QS_OVERALL       7061 non-null float64
REG_FEE          7109 non-null int64
COMMIS           7109 non-null int64
SALES_PRICE      7109 non-null int64
dtypes: float64(6), int64(6), object(10)
memory usage: 1.

In [104]:
train_data.describe()

INT_SQFT  DIST_MAINROAD    N_BEDROOM   N_BATHROOM       N_ROOM  \
count  7109.000000    7109.000000  7108.000000  7104.000000  7109.000000   
mean   1382.073006      99.603179     1.637029     1.213260     3.688704   
std     457.410902      57.403110     0.802902     0.409639     1.019099   
min     500.000000       0.000000     1.000000     1.000000     2.000000   
25%     993.000000      50.000000     1.000000     1.000000     3.000000   
50%    1373.000000      99.000000     1.000000     1.000000     4.000000   
75%    1744.000000     148.000000     2.000000     1.000000     4.000000   
max    2500.000000     200.000000     4.000000     2.000000     6.000000   

          QS_ROOMS  QS_BATHROOM   QS_BEDROOM   QS_OVERALL        REG_FEE  \
count  7109.000000  7109.000000  7109.000000  7061.000000    7109.000000   
mean      3.517471     3.507244     3.485300     3.503254  376938.330708   
std       0.891972     0.897834     0.887266     0.527223  143070.662010   
min       2.000000     2.000000     2.000000     2.000000   71177.000000   
25%       2.700000     2.700000     2.700000     3.130000  272406.000000   
50%       3.500000     3.500000     3.500000     3.500000  349486.000000   
75%       4.300000     4.300000     4.300000     3.890000  451562.000000   
max       5.000000     5.000000     5.000000     4.970000  983922.000000   

              COMMIS   SALES_PRICE  
count    7109.000000  7.109000e+03  
mean   141005.726544  1.089491e+07  
std     78768.093718  3.768603e+06  
min      5055.000000  2.156875e+06  
25%     84219.000000  8.272100e+06  
50%    127628.000000  1.033505e+07  
75%    184506.000000  1.299390e+07  
max    495405.000000  2.366734e+07

In [105]:
import numpy as np

In [106]:
shuffled_indices = np.random.permutation(7109)

In [107]:
train_data = train_data.iloc[shuffled_indices]

In [108]:
train_data.shape

(7109, 22)

In [109]:
corr_matrix = training_data.corr()

In [110]:
corr_matrix["SALES_PRICE"].sort_values()

REG_FEE_per_COMMIS    -0.082844
QS_BATHROOM           -0.011377
DIST_MAINROAD          0.018783
QS_BEDROOM             0.018804
QS_OVERALL             0.020556
QS_ROOMS               0.021967
N_BATHROOM             0.108884
N_BEDROOM              0.330999
REG_FEE_into_COMMIS    0.451212
N_ROOM                 0.602760
INT_SQFT               0.612125
COMMIS                 0.626275
REG_FEE                0.878148
SALES_PRICE            1.000000
Name: SALES_PRICE, dtype: float64

In [111]:
training_data = train_data.copy()

In [112]:
training_data["REG_FEE_into_COMMIS"]=training_data["N_ROOM"]+training_data["N_BEDROOM"]+training_data["N_BATHROOM"]

In [113]:
from sklearn.base import TransformerMixin,BaseEstimator
class DataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self,attribute_names):
        self.attribute_names = attribute_names
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attribute_names].values

In [114]:
from sklearn.preprocessing import LabelBinarizer
class LabelBinarizer_new(TransformerMixin, BaseEstimator):
    def fit(self, X, y = 0):
        self.encoder = None
        return self
    def transform(self, X, y = 0):
        if(self.encoder is None):
            print("Initializing encoder")
            self.encoder = LabelBinarizer();
            result = self.encoder.fit_transform(X)
        else:
            result = self.encoder.transform(X)
        return result; 

In [115]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import Imputer,StandardScaler

In [116]:
num_attribs = ["INT_SQFT","N_BEDROOM","N_BATHROOM","N_ROOM","REG_FEE","COMMIS"]
cat_attribs = ["AREA","SALE_COND","PARK_FACIL","UTILITY_AVAIL","STREET","MZZONE"]

In [117]:
num_pipeline = Pipeline([('selector',DataFrameSelector(num_attribs)),('imputer',Imputer(strategy='median')),('std_scaler',StandardScaler())])

In [183]:
cat_pipeline1 = Pipeline([('selector',DataFrameSelector(["AREA"])),('label_binarizer',LabelBinarizer_new())])
cat_pipeline2 = Pipeline([('selector',DataFrameSelector(["SALE_COND"])),('label_binarizer',LabelBinarizer_new())])
cat_pipeline3 = Pipeline([('selector',DataFrameSelector(["PARK_FACIL"])),('label_binarizer',LabelBinarizer_new())])
cat_pipeline4 = Pipeline([('selector',DataFrameSelector(["UTILITY_AVAIL"])),('label_binarizer',LabelBinarizer_new())])
cat_pipeline5 = Pipeline([('selector',DataFrameSelector(["STREET"])),('label_binarizer',LabelBinarizer_new())])
cat_pipeline6 = Pipeline([('selector',DataFrameSelector(["MZZONE"])),('label_binarizer',LabelBinarizer_new())])


In [167]:
from sklearn.pipeline import FeatureUnion

In [184]:
full_pipeline = FeatureUnion(transformer_list = [("num_pipeline",num_pipeline),("cat_pipeline1",cat_pipeline1)])

In [169]:
X_train = train_data.drop("SALES_PRICE",axis =1)

In [170]:
y_train = train_data["SALES_PRICE"]

In [185]:
X_prepared = full_pipeline.fit_transform(X_train)

Initializing encoder


In [186]:
X_prepared.shape

(7109, 23)

In [139]:
from sklearn.linear_model import LinearRegression,SGDRegressor
from sklearn.ensemble import RandomForestRegressor

In [140]:
lin_reg = LinearRegression()
sgd_reg = SGDRegressor()
forest_reg = RandomForestRegressor()

In [141]:
from sklearn.model_selection import cross_val_score

In [142]:
cross_val_score(lin_reg,X_prepared,y_train,cv=3,scoring='neg_mean_squared_error')

array([-1.53855914e+12, -1.62899752e+12, -1.48832042e+12])

In [143]:
cross_val_score(sgd_reg,X_prepared,y_train,cv=3,scoring='neg_mean_squared_error')

/home/shruti/analytics_vidya_competitions/env/lib/python3.5/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDRegressor'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/shruti/analytics_vidya_competitions/env/lib/python3.5/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDRegressor'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." %

array([-1.58169897e+12, -1.70225667e+12, -1.56075523e+12])

In [146]:
cross_val_score(forest_reg,X_prepared,y_train,cv=3,scoring='neg_mean_squared_error')

array([-1.28112059e+12, -1.38110091e+12, -1.30633480e+12])

In [145]:
forest_reg.fit(X_prepared,y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [132]:
X_prepared.shape

(7109, 51)

In [133]:
from sklearn.model_selection import GridSearchCV

In [147]:
X_test_prepared = full_pipeline.transform(test_data)

In [153]:
y_pred = forest_reg.predict(X_test_prepared)
ids = test_data['PRT_ID'].values
ids

array(['P05996', 'P09294', 'P03807', ..., 'P00474', 'P08173', 'P00643'],
      dtype=object)

In [154]:
y_pred = pd.DataFrame(np.c_[ids,y_pred],columns=["PRT_ID","SALES_PRICE"])

In [155]:
y_pred.to_csv('submission_vidya2.csv',index=False)

In [157]:
from sklearn.ensemble import GradientBoostingRegressor

In [160]:
gbrt = GradientBoostingRegressor(n_estimators=50)

In [161]:
cross_val_score(gbrt,X_prepared,y_train,cv=3,scoring="neg_mean_squared_error")

array([-1.35379527e+12, -1.42513892e+12, -1.33486797e+12])

In [174]:
from sklearn.svm import SVR

In [177]:
svr = SVR(gamma=0.03)

In [178]:
cross_val_score(svr,X_prepared,y_train,cv=3,scoring="neg_mean_squared_error")

array([-1.40740649e+13, -1.51052026e+13, -1.43577470e+13])

In [165]:
from sklearn.preprocessing import LabelEncoder

In [179]:
X_prepared.shape

(7109, 6)

In [226]:
from sklearn.model_selection import GridSearchCV
param_grid = {'n_iter':[500,1000,2000],'eta0':[0.01]}

In [227]:
from sklearn.linear_model import SGDRegressor

In [228]:
sgd_reg = SGDRegressor()

In [229]:
grid_search = GridSearchCV(sgd_reg,param_grid,cv = 3,scoring='neg_mean_squared_error')

In [230]:
grid_search.fit(X_prepared,y_train)

/home/shruti/analytics_vidya_competitions/env/lib/python3.5/site-packages/sklearn/linear_model/stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)
/home/shruti/analytics_vidya_competitions/env/lib/python3.5/site-packages/sklearn/linear_model/stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)
/home/shruti/analytics_vidya_competitions/env/lib/python3.5/site-packages/sklearn/linear_model/stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)
/home/shruti/analytics_vidya_competitions/env/lib/python3.5/site-packages/sklearn/linear_model/stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. 

GridSearchCV(cv=3, error_score='raise',
       estimator=SGDRegressor(alpha=0.0001, average=False, epsilon=0.1, eta0=0.01,
       fit_intercept=True, l1_ratio=0.15, learning_rate='invscaling',
       loss='squared_loss', max_iter=None, n_iter=None, penalty='l2',
       power_t=0.25, random_state=None, shuffle=True, tol=None, verbose=0,
       warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'n_iter': [500, 1000, 2000], 'eta0': [0.01]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='neg_mean_squared_error', verbose=0)

In [231]:
grid_search.best_params_

{'eta0': 0.01, 'n_iter': 2000}

In [232]:
cross_val_score(sgd_reg,X_prepared,y_train,cv=3,scoring='neg_mean_squared_error')

/home/shruti/analytics_vidya_competitions/env/lib/python3.5/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDRegressor'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/home/shruti/analytics_vidya_competitions/env/lib/python3.5/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDRegressor'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." %

array([-1.58780087e+12, -1.70894217e+12, -1.56500625e+12])