In [1]:
import pandas as pd

In [2]:
train_data = pd.read_csv('train_Vidya2.csv')

In [3]:
test_data = pd.read_csv('test_Vidya2.csv')

In [19]:
train_data.head()

PRT_ID        AREA  INT_SQFT  DATE_SALE  DIST_MAINROAD  N_BEDROOM  \
0  P03210  Karapakkam      1004       2011            3.0        1.0   
1  P09411  Anna Nagar      1986       2006            1.0        2.0   
2  P01812       Adyar       909       2012            2.0        1.0   
3  P05346   Velachery      1855       2010            1.0        3.0   
4  P06210  Karapakkam      1226       2009            2.0        1.0   

   N_BATHROOM  N_ROOM SALE_COND PARK_FACIL     ...       UTILITY_AVAIL  \
0         1.0       3  AbNormal        Yes     ...              AllPub   
1         1.0       5  AbNormal         No     ...              AllPub   
2         1.0       3  AbNormal        Yes     ...                 ELO   
3         2.0       5    Family         No     ...             NoSewr    
4         1.0       3  AbNormal        Yes     ...              AllPub   

   STREET MZZONE QS_ROOMS QS_BATHROOM  QS_BEDROOM  QS_OVERALL  REG_FEE  \
0   Paved      C      8.0         8.0        10.0         9.0   380000   
1  Gravel     RH     10.0         9.0         5.0         8.0   760122   
2  Gravel     RL      9.0         8.0         5.0         7.0   421094   
3   Paved      C     10.0         8.0         8.0         9.0   356321   
4  Gravel      C      6.0         5.0         9.0         7.0   237000   

   COMMIS  SALES_PRICE  
0  144400      7600000  
1  304049     21717770  
2   92114     13159200  
3   77042      9630290  
4   74063      7406250  

[5 rows x 22 columns]

In [48]:
test_data['AREA'].replace(to_replace="Adyr",value="Adyar",inplace=True)
test_data['AREA'].replace(to_replace="KKNagar",value="KK Nagar",inplace=True)
test_data['AREA'].replace(to_replace="Ann Nagar",value="Anna Nagar",inplace=True)
test_data['AREA'].replace(to_replace="Velchery",value="Velachery",inplace=True)
test_data['AREA'].replace(to_replace="Ana Nagar",value="Anna Nagar",inplace=True)
test_data['AREA'].replace(to_replace="Karapakam",value="Karapakkam",inplace=True)
test_data['AREA'].replace(to_replace="TNagar",value="T Nagar",inplace=True)
test_data['AREA'].replace(to_replace="Chormpet",value="Chrompet",inplace=True)
test_data['AREA'].replace(to_replace="Chrmpet",value="Chrompet",inplace=True)
test_data['AREA'].replace(to_replace="Chrompt",value="Chrompet",inplace=True)

In [49]:
test_data['DATE_SALE'] = test_data['DATE_SALE'].apply(lambda x: int(str(x)[-4:]))

In [50]:
import numpy as np
test_data["DIST_MAINROAD"]=np.ceil(test_data["DIST_MAINROAD"]/50)

In [51]:
test_data['SALE_COND'].replace(to_replace="Adj Land",value="AdjLand",inplace=True)
test_data['SALE_COND'].replace(to_replace="Ab Normal",value="AbNormal",inplace=True)
test_data['SALE_COND'].replace(to_replace="Partiall",value="Partial",inplace=True)
test_data['SALE_COND'].replace(to_replace="PartiaLl",value="Partial",inplace=True)

In [52]:
test_data['PARK_FACIL'].replace(to_replace="Noo",value="No",inplace=True)

In [53]:
test_data['UTILITY_AVAIL'].replace(to_replace="All Pub",value="AllPub",inplace=True)

In [54]:
test_data['STREET'].replace(to_replace="Pavd",value="Paved",inplace=True)
test_data['STREET'].replace(to_replace="NoAccess",value="No Access",inplace=True)

In [55]:
test_data['MZZONE'].replace(to_replace="A",value="C",inplace=True)
test_data['MZZONE'].replace(to_replace="I",value="C",inplace=True)

In [56]:
test_data['DATE_BUILD'] = test_data['DATE_BUILD'].apply(lambda x: int(str(x)[-4:]))

In [57]:
test_data['BUILDTYPE'].replace(to_replace="Other",value="Others",inplace=True)
test_data['BUILDTYPE'].replace(to_replace="Comercial",value="Commercial",inplace=True)

In [58]:
test_data["QS_OVERALL"]=np.ceil(train_data["QS_OVERALL"]/0.5)

In [59]:
test_data["QS_BEDROOM"]=np.ceil(train_data["QS_BEDROOM"]/0.5)

In [60]:
test_data["QS_BATHROOM"]=np.ceil(train_data["QS_BATHROOM"]/0.5)

In [61]:
test_data["QS_ROOMS"]=np.ceil(train_data["QS_ROOMS"]/0.5)

In [20]:
num_attribs = ["INT_SQFT","N_BEDROOM","N_BATHROOM","N_ROOM","REG_FEE","COMMIS","DATE_SALE","DIST_MAINROAD","QS_ROOMS","QS_BATHROOM","QS_BEDROOM","QS_OVERALL","DATE_BUILD"]
cat_attribs = ["AREA","SALE_COND","PARK_FACIL","UTILITY_AVAIL","STREET","MZZONE","BUILDTYPE"]

In [21]:
y_train = train_data["SALES_PRICE"].copy()

In [22]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import Imputer,StandardScaler

In [23]:
from sklearn.base import TransformerMixin,BaseEstimator
class DataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self,attribute_names):
        self.attribute_names = attribute_names
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attribute_names].values

In [24]:
from sklearn.preprocessing import LabelBinarizer
class LabelBinarizer_new(TransformerMixin, BaseEstimator):
    def fit(self, X, y = 0):
        self.encoder = None
        return self
    def transform(self, X, y = 0):
        if(self.encoder is None):
            print("Initializing encoder")
            self.encoder = LabelBinarizer();
            result = self.encoder.fit_transform(X)
        else:
            result = self.encoder.transform(X)
        return result; 

In [25]:
cat_pipeline1 = Pipeline([('selector',DataFrameSelector(["AREA"])),('label_binarizer',LabelBinarizer_new())])
cat_pipeline2 = Pipeline([('selector',DataFrameSelector(["SALE_COND"])),('label_binarizer',LabelBinarizer_new())])
cat_pipeline3 = Pipeline([('selector',DataFrameSelector(["PARK_FACIL"])),('label_binarizer',LabelBinarizer_new())])
cat_pipeline4 = Pipeline([('selector',DataFrameSelector(["UTILITY_AVAIL"])),('label_binarizer',LabelBinarizer_new())])
cat_pipeline5 = Pipeline([('selector',DataFrameSelector(["STREET"])),('label_binarizer',LabelBinarizer_new())])
cat_pipeline6 = Pipeline([('selector',DataFrameSelector(["MZZONE"])),('label_binarizer',LabelBinarizer_new())])
cat_pipeline7 = Pipeline([('selector',DataFrameSelector(["BUILDTYPE"])),('label_binarizer',LabelBinarizer_new())])

In [36]:
num_pipeline = Pipeline([('selector',DataFrameSelector(num_attribs)),('imputer',Imputer(strategy='median'))])

In [37]:
from sklearn.pipeline import FeatureUnion

In [38]:
full_pipeline = FeatureUnion(transformer_list = [("num_pipeline",num_pipeline),("cat_pipeline1",cat_pipeline1),("cat_pipeline2",cat_pipeline2),("cat_pipeline3",cat_pipeline3),("cat_pipeline4",cat_pipeline4),("cat_pipeline5",cat_pipeline5),("cat_pipeline6",cat_pipeline6),("cat_pipeline7",cat_pipeline7)])

In [29]:
X_train1 = full_pipeline.fit_transform(train_data)

Initializing encoder
Initializing encoder
Initializing encoder
Initializing encoder
Initializing encoder
Initializing encoder
Initializing encoder


In [30]:
from sklearn.linear_model import LinearRegression

In [33]:
lin_reg = LinearRegression()

In [34]:
from sklearn.model_selection import cross_val_score

In [35]:
cross_val_score(lin_reg,X_train1,y_train,cv=5,scoring="neg_mean_squared_error")

array([-4.78873041e+11, -5.10770710e+11, -5.02500262e+11, -5.06641412e+11,
       -5.32919109e+11])

In [39]:
X_train2 = full_pipeline.fit_transform(train_data)

Initializing encoder
Initializing encoder
Initializing encoder
Initializing encoder
Initializing encoder
Initializing encoder
Initializing encoder


In [40]:
from sklearn.ensemble import RandomForestRegressor

In [46]:
forest_reg = RandomForestRegressor()


In [47]:
cross_val_score(forest_reg,X_train2,y_train,cv=5,scoring="neg_mean_squared_error")

array([-3.98212638e+11, -4.19000873e+11, -4.43620213e+11, -4.03096648e+11,
       -3.89546431e+11])

In [43]:
from sklearn.svm import SVR

In [44]:
svr_reg = SVR()

In [45]:
cross_val_score(svr_reg,X_train1,y_train,cv=5,scoring="neg_mean_squared_error")

array([-1.39563974e+13, -1.46760003e+13, -1.46141254e+13, -1.32903004e+13,
       -1.60378503e+13])

In [63]:
X_test2 = full_pipeline.transform(test_data)
forest_reg.fit(X_train2,y_train)
#y_pred = forest_reg.predict(X_test2)
#ids = test_data['PRT_ID'].value

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [125]:
y_pred = ada_reg.predict(X_test2)
ids = test_data['PRT_ID'].values
y_pred

array([ 7746131.78188761, 14795541.1188526 ,  8397466.79708928, ...,
       18168931.82994423, 15346898.3703382 , 13439552.94177375])

In [126]:
y_pred = pd.DataFrame(np.c_[ids,y_pred],columns=["PRT_ID","SALES_PRICE"])

In [127]:
y_pred.to_csv('submission_vidya2.csv',index=False)

In [70]:
from sklearn.ensemble import BaggingRegressor

In [71]:
bag_reg = BaggingRegressor(RandomForestRegressor(),n_estimators = 500,bootstrap=True,n_jobs=-1,oob_score=True)

In [72]:
bag_reg.fit(X_train2,y_train)

BaggingRegressor(base_estimator=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=500, n_jobs=-1, oob_score=True,
         random_state=None, verbose=0, warm_start=False)

In [73]:
bag_reg.oob_score_

0.9749196749477045

In [83]:
from sklearn.ensemble import GradientBoostingRegressor

In [113]:
gbrt = GradientBoostingRegressor(n_estimators = 2000)

In [111]:
cross_val_score(gbrt,X_train2,y_train,cv=5,scoring="neg_mean_squared_error")

array([-2.28760683e+11, -2.32079973e+11, -2.51624077e+11, -2.20915564e+11,
       -2.13105793e+11])

In [102]:
gbrt.fit(X_train2,y_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.1, loss='ls', max_depth=3, max_features=None,
             max_leaf_nodes=None, min_impurity_decrease=0.0,
             min_impurity_split=None, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             n_estimators=2000, presort='auto', random_state=None,
             subsample=1.0, verbose=0, warm_start=False)

In [106]:
svr_reg = SVR(gamma=10,C=1000)

In [107]:
cross_val_score(svr_reg,X_train2,y_train,cv=5,scoring="neg_mean_squared_error")

array([-1.39578982e+13, -1.46779092e+13, -1.46158039e+13, -1.32918276e+13,
       -1.60396211e+13])

In [112]:
from sklearn.ensemble import AdaBoostRegressor

In [123]:
ada_reg = AdaBoostRegressor(GradientBoostingRegressor(n_estimators=2000),n_estimators=50)

In [117]:
cross_val_score(ada_reg,X_train2,y_train,cv=5,scoring="neg_mean_squared_error")

KeyboardInterrupt: 

In [124]:
ada_reg.fit(X_train2,y_train)

AdaBoostRegressor(base_estimator=GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.1, loss='ls', max_depth=3, max_features=None,
             max_leaf_nodes=None, min_impurity_decrease=0.0,
             min_impurity_split=None, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             n_estimators=2000, presort='auto', random_state=None,
             subsample=1.0, verbose=0, warm_start=False),
         learning_rate=1.0, loss='linear', n_estimators=50,
         random_state=None)